let ten: (string | number)[] = ['petya', 12, 'galya', 18, 'serega', 36, 'dima', 24, 'larisa ivanovna', 54];
console.log(ten[0]);
console.log(ten[1]);
console.log(ten[2]);
console.log(ten[3]);
console.log(ten[4]);
console.log(ten[5]);
console.log(ten[6]);
console.log(ten[7]);
console.log(ten[8]);
console.log(ten[9]);